services:
    bot:
        image: ghcr.io/romanychev-l/habitry/bot:latest
        restart: unless-stopped
        env_file:
            - .env
        network_mode: host
        init: true
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

    backend:
        image: ghcr.io/romanychev-l/habitry/backend:latest
        network_mode: host
        env_file:
            - .env
        restart: unless-stopped
        init: true
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"